language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew install opam
  - opam init
  - opam switch "$OCAML_VERSION"
  - eval `opam config env`
  - opam update
  - opam install -y re
before_script:
  - opam pin add -y ReasonNativeProject .
script:
  - make run
  - git diff --exit-code
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
notifications:
  email:
    - yunxing@fb.com
    - reason@cloudwalk.me
